import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import WhatMakes from "../components/WhatMakes";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Halalanft</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.png" />
			</Head>
			<Navbar />
			<Hero />
			<About />
			<WhatMakes />
		</div>
	);
}
