name: Production - Halalanft

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'frontend/apps/**'

jobs:
  check:
    name: Check (deny warning, fmt, clippy)
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --manifest-path frontend/apps/Cargo.toml

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path frontend/apps/Cargo.toml -- --check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name: make nightly the default
        run: rustup default nightly
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install npm deps
        run: npm ci
        working-directory: "./frontend/apps"
      - name: build frontend
        run: npm run build
        working-directory: "./frontend/apps"
      - name: Vercel Action
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.PROJECT_GITHUB_TOKEN }} #Optional 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          working-directory: ./frontend/apps/devhtml